debug: False

output_path:
pretrained_model:
device_id: [ 0 ]
cuda_visible_device: '0'

# loss_function
loss: 'cross_entropy'

data_param:
  type: "UT_HAR"
  class_num: 7
  batch_size: 128
  workers: 10
  pin_memory: False
  drop_last: False
  dataset_mode: [ "train", "val" ]

  train_data_param:
    data_path: /media/sda/LeiH/Dataset/UT_HAR/data
    label_path: /media/sda/LeiH/Dataset/UT_HAR/label
  val_data_param:
    data_path: /media/sda/LeiH/Dataset/UT_HAR/data
    label_path: /media/sda/LeiH/Dataset/UT_HAR/label


# model = KAN([28 * 28, 64, 10])
# model
model_param:
  type: 'KAN'
  layers_hidden: [0,1024]
  input_T: 250
  input_S: 90
  grid_size: 10
  spline_order: 3
  scale_noise: 0.1
  scale_base: 1.0
  scale_spline: 1.0
  base_activation: SiLU
  grid_eps: 0.02
  grid_range: [-1, 1]
# head_param is for build_head
head_param:
  type: 'SimpleHead'
  num_classes: 7
  in_channels: 1024


# optimizer_param is for build_optimizer
optimizer_param:
  optim_type: 'adam'
  lr: 0.01
  wd: 0


# training_param is for class TrainingEngine
training_param:
  dataloader_datatype: 'N1TW'
  model_datatype: 'N*'
  max_epoch: 300
  val_frequency: 1
  save_frequency: 1





